name: llama_vision_env
channels:
  - conda-forge
  - defaults
variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pillow
  - matplotlib
  - tqdm
  - pyyaml
  - scikit-learn
  - pip
  - pip:
    # Core dependencies for data generation and evaluation
    - transformers==4.45.2  # Fixed version for Llama-3.2-Vision compatibility
    - typer>=0.9.0
    - rich>=13.0.0
    - torch>=2.0.0
    - torchvision
    - accelerate  # Required for MPS/device mapping support
    - bitsandbytes  # Required for 8-bit quantization on V100 16GB
    - sentencepiece  # Required for tokenizer
    - protobuf  # Required for model loading

# Usage Instructions:
# -----------------
# V100 16GB Production Environment:
# conda env create -f environment.yml
# conda activate llama_vision_env
# 
# For CUDA 11.x (V100):
# conda install pytorch==2.0.1 torchvision==0.15.2 pytorch-cuda=11.8 -c pytorch -c nvidia
#
# For CUDA 12.x (L40S):
# conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
#
# Note: 
# - transformers is pinned to 4.45.2 for Llama-3.2-Vision compatibility
# - bitsandbytes is required for 8-bit quantization on V100 16GB
# - KMP_DUPLICATE_LIB_OK=TRUE is automatically set to fix OpenMP library conflicts